sonar.projectKey=reyes-magos-p-i_p.i-bases-software_grupo-3
sonar.organization=reyes-magos-p-i

# source and test convention definition
sonar.sources=apps
sonar.tests=apps
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.js,**/*.test.js

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/*.test.ts

sonar.verbose=true
sonar.javascript.lcov.reportPaths=apps/api/coverage/lcov.info,apps/web/coverage/lcov.info