-- =========================================================
-- SECTION: Geographic Locations
-- =========================================================
CREATE TABLE Provinces (
    id_province     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100) NOT NULL
);

CREATE TABLE Cantons (
    id_canton       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100) NOT NULL,
    id_province     NUMBER NOT NULL,
    CONSTRAINT fk_canton_province
        FOREIGN KEY (id_province) REFERENCES Provinces (id_province)
);

CREATE TABLE Districts (
    id_district     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100) NOT NULL,
    id_canton       NUMBER NOT NULL,
    CONSTRAINT fk_district_canton
        FOREIGN KEY (id_canton) REFERENCES Cantons (id_canton)
);

CREATE TABLE Addresses (
    id_address      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_district     NUMBER NOT NULL,
    details         VARCHAR2(255),  -- opcional
    CONSTRAINT fk_address_district
        FOREIGN KEY (id_district) REFERENCES Districts (id_district)
);

-- =========================================================
-- SECTION: Users (employees and clients)
-- =========================================================
CREATE TABLE Employees (
    employee_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR2(100) NOT NULL,
    second_name     VARCHAR2(100),
    first_surname   VARCHAR2(100) NOT NULL,
    second_surname  VARCHAR2(100),
    birthday        DATE NOT NULL,
    phone_number    VARCHAR2(20) NOT NULL,
    email           VARCHAR2(150) NOT NULL UNIQUE,
    role            VARCHAR2(50) NOT NULL,
    id_address      NUMBER NOT NULL,
    CONSTRAINT fk_employee_address
        FOREIGN KEY (id_address) REFERENCES Addresses (id_address)
);

CREATE TABLE Clients (
    client_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR2(100) NOT NULL,
    second_name     VARCHAR2(100),
    first_surname   VARCHAR2(100) NOT NULL,
    second_surname  VARCHAR2(100),
    birthday        DATE NOT NULL,
    phone_number    VARCHAR2(20) NOT NULL,
    -- email           VARCHAR2(150) NOT NULL UNIQUE,
    id_address      NUMBER NOT NULL,
    CONSTRAINT fk_client_address
        FOREIGN KEY (id_address) REFERENCES Addresses (id_address)
);

-- =========================================================
-- SECTION: Companies / Cinemas
-- =========================================================
CREATE TABLE Companies (
    company_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name            VARCHAR2(150) NOT NULL,
    id_address              NUMBER NOT NULL,
    email                   VARCHAR2(254) NOT NULL,
    phone                   NUMBER NOT NULL,
    CONSTRAINT fk_company_address
        FOREIGN KEY (id_address) REFERENCES Addresses (id_address)
);

CREATE TABLE Cinemas (
    cinema_id       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100) NOT NULL,
    company_id      NUMBER NOT NULL,
    CONSTRAINT fk_cinemas_companies FOREIGN KEY (company_id) REFERENCES Companies(company_id)
);

-- =========================================================
-- SECTION: Movies catalog
-- =========================================================
CREATE TABLE Clasifications (
    clasification_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clasification_name         VARCHAR2(10) NOT NULL,
    clasification_description  VARCHAR2(300),
    CONSTRAINT uq_clasifications_name UNIQUE (clasification_name)
);

CREATE TABLE Languages (
    language_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR2(2) NOT NULL,
    CONSTRAINT uq_languages_code UNIQUE (code)
);

CREATE TABLE Genres (
    genre_id    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    CONSTRAINT uq_genres_name UNIQUE (name)
);

CREATE TABLE Movies (
    movie_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               VARCHAR2(100) NOT NULL,
    running_time        NUMBER NOT NULL,
    synopsis            VARCHAR2(500) NOT NULL,
    poster_image        VARCHAR2(200) NOT NULL,
    release_year        NUMBER(4) NOT NULL,
    clasification_id   NUMBER,
    CONSTRAINT fk_movie_clasification
        FOREIGN KEY (clasification_id) REFERENCES clasifications (clasification_id),
    CONSTRAINT chk_movie_running_time
        CHECK (running_time > 0)
);

CREATE TABLE Movie_genres (
    movie_id        NUMBER NOT NULL,
    genre_id        NUMBER NOT NULL,
    CONSTRAINT pk_movie_genres PRIMARY KEY (movie_id, genre_id),
    CONSTRAINT fk_movie_genres_movie
        FOREIGN KEY (movie_id) REFERENCES Movies (movie_id),

    CONSTRAINT fk_movie_genres_genre
        FOREIGN KEY (genre_id) REFERENCES Genres (genre_id)
);

CREATE TABLE Movie_languages (
    movie_id        NUMBER NOT NULL,
    language_id     NUMBER NOT NULL,
    CONSTRAINT pk_movie_languages PRIMARY KEY (movie_id, language_id),
    CONSTRAINT fk_movlang_movid
        FOREIGN KEY (movie_id) REFERENCES Movies (movie_id),
    CONSTRAINT fk_movlang_langid
        FOREIGN KEY (language_id) REFERENCES Languages (language_id)
);


CREATE TABLE Invoices (
    invoice_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       NUMBER NOT NULL,
    total           NUMBER(12,2) NOT NULL,

    CONSTRAINT fk_invoice_client
        FOREIGN KEY (client_id) REFERENCES Clients (client_id),

    CONSTRAINT chk_invoice_total
        CHECK (total >= 0)
);

CREATE TABLE Invoice_products
(
    invoice_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    CONSTRAINT invoice_products_pk PRIMARY KEY (invoice_id, product_id)
    CONSTRAINT FK_invoice_id FOREIGN KEY(invoice_id) REFERENCES Invoices(invoice_id)
    CONSTRAINT FK_product_id FOREIGN KEY(product_id) REFERENCES Products(product_id)
)

CREATE TABLE Theaters
(
    theater_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cinema_id NUMBER NOT NULL,
    number_seats NUMBER NOT NULL,
    dimension_x NUMBER,
    dimension_y NUMBER,
    projector_type VARCHAR2(100),
    sound_system VARCHAR2(100),
    CONSTRAINT FK_cinema_theater FOREIGN KEY (cinema_id) REFERENCES Cinemas(cinema_id)
);

CREATE TABLE Movie_languages
(
    movie_id NUMBER NOT NULL,
    language_id NUMBER NOT NULL,
    CONSTRAINT PK_movie_languages PRIMARY KEY (movie_id, language_id),
    CONSTRAINT FK_movlang_movID FOREIGN KEY(movie_id) REFERENCES Movies(movie_id),
    CONSTRAINT FK_movlang_langID FOREIGN KEY(language_id) REFERENCES Languages(language_id)
);

-- =========================================================
-- SECTION: Credentials
--   - Employees: only local_credentials (for security reasons, no OAuth)
--   - Clients: can have external_credentials, local_credentials,
--     or both, in any order. None are required at the database level;
--     the only business rule (that a client must have at least one login method)
--     is validated in the application, not here.
-- =========================================================
CREATE TABLE Employee_local_credentials (
    credentials_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     NUMBER NOT NULL UNIQUE,
    password_hash   VARCHAR2(255) NOT NULL,
    salt            VARCHAR2(100) NOT NULL,
    CONSTRAINT fk_emp_local_cred_employee
        FOREIGN KEY (employee_id) REFERENCES Employees (employee_id)
);

/* googl authentication needs more research
CREATE TABLE user_mfa (
    user_id INT PRIMARY KEY,
    encrypted_secret_key VARCHAR(255) NOT NULL,
    is_mfa_enabled BOOLEAN DEFAULT FALSE,
    backup_codes TEXT -- Encrypted list of emergency recovery codes
);
*/

CREATE TABLE Client_external_credentials (
    external_credentials_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id             NUMBER NOT NULL,
    provider_name         VARCHAR2(50) NOT NULL,
    provider_user_id      VARCHAR2(255) NOT NULL,
    email                 VARCHAR2(150),
    access_token          VARCHAR2(2000),
    refresh_token         VARCHAR2(2000),
    token_expires_at      TIMESTAMP,
    created_at            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_client_ext_cred_client
        FOREIGN KEY (client_id) REFERENCES Clients (client_id),
    CONSTRAINT chk_client_ext_provider
        CHECK (provider_name IN ('GOOGLE', 'FACEBOOK')),
    CONSTRAINT uq_client_ext_cred_client_provider
        UNIQUE (client_id, provider_name),
    CONSTRAINT uq_client_ext_cred_provider_account
        UNIQUE (provider_name, provider_user_id)
);

CREATE TABLE Client_local_credentials (
    credentials_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       NUMBER NOT NULL UNIQUE,
    password_hash   VARCHAR2(255) NOT NULL,
    salt            VARCHAR2(100) NOT NULL,
    CONSTRAINT fk_client_local_cred_client
        FOREIGN KEY (client_id) REFERENCES Clients (client_id)
);

-- =========================================================
-- SECTION: Activities and Movie Functions
-- =========================================================
CREATE TABLE Activities (
    activity_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100) NOT NULL,
    duration        INTERVAL DAY TO SECOND NOT NULL,
    type            VARCHAR2(50) NOT NULL,
    description     VARCHAR2(500),
    CONSTRAINT chk_activity_type
        CHECK (type IN ('CLEANING', 'MAINTENANCE', 'ADVERTISEMENT'))
);

CREATE TABLE Movie_functions (
    movie_function_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id            NUMBER NOT NULL,
    theater_id           NUMBER NOT NULL,
    start_time            TIMESTAMP NOT NULL,
    end_time              TIMESTAMP NOT NULL,
    screening_date         DATE NOT NULL,
    created_by             NUMBER NOT NULL,
    CONSTRAINT fk_movie_function_employee
        FOREIGN KEY (created_by) REFERENCES Employees (employee_id),
    CONSTRAINT fk_movie_function_movie
        FOREIGN KEY (movie_id) REFERENCES Movies (movie_id),
    CONSTRAINT fk_movie_function_theater
        FOREIGN KEY (theater_id) REFERENCES Theaters (theater_id),
    CONSTRAINT uq_movie_function UNIQUE (movie_id, theater_id, start_time, end_time),
    CONSTRAINT chk_movie_function_times
        CHECK (end_time > start_time)
);

CREATE TABLE Tickets (
    ticket_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_function_id   NUMBER NOT NULL,
    invoice_id          NUMBER NOT NULL,
    seat                VARCHAR2(10) NOT NULL,
    price_paid          NUMBER(12,2) NOT NULL,

    CONSTRAINT fk_ticket_movie_function
        FOREIGN KEY (movie_function_id)
        REFERENCES Movie_functions (movie_function_id),

    CONSTRAINT fk_ticket_invoice
        FOREIGN KEY (invoice_id)
        REFERENCES Invoices (invoice_id),

    CONSTRAINT uq_ticket_function_seat
        UNIQUE (movie_function_id, seat),

    CONSTRAINT chk_ticket_price_paid
        CHECK (price_paid >= 0)
);

CREATE TABLE Movie_functions_activities (
    movie_functions_activity_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_function_id            NUMBER NOT NULL,
    activity_id                  NUMBER NOT NULL,
    created_by                   NUMBER NOT NULL,
    CONSTRAINT fk_mfa_movie_function
        FOREIGN KEY (movie_function_id) REFERENCES Movie_functions (movie_function_id),
    CONSTRAINT fk_mfa_activity
        FOREIGN KEY (activity_id) REFERENCES Activities (activity_id),
    CONSTRAINT fk_mfa_employee
        FOREIGN KEY (created_by) REFERENCES Employees (employee_id),
    CONSTRAINT uq_mfa_function_activity
        UNIQUE (movie_function_id, activity_id)
);

CREATE TABLE Products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100),
    price NUMBER NOT NULL,
    is_ticket BOOLEAN NOT NULL,
    
);
