-- =========================================================
-- SCRUM-42..45: projection scheduling (movie_functions)
--
-- Run connected as PRODUCTION (or with CURRENT_SCHEMA = PRODUCTION).
-- START_TIME / END_TIME are stored in Costa Rica local time
-- (TIMESTAMP without time zone), exactly as the form sends them.
-- =========================================================

-- ---------------------------------------------------------
-- 1. Movies available per branch
--    The form search only offers movies with IS_AVAILABLE = 1
--    in the branch of the selected theater.
-- ---------------------------------------------------------
CREATE TABLE Cinema_movies (
    branch_id       NUMBER NOT NULL,
    movie_id        NUMBER NOT NULL,
    is_available    NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT pk_cinema_movies PRIMARY KEY (branch_id, movie_id),
    CONSTRAINT fk_cinema_movies_cinema
        FOREIGN KEY (branch_id) REFERENCES Cinemas (branch_id),
    CONSTRAINT fk_cinema_movies_movie
        FOREIGN KEY (movie_id) REFERENCES Movies (movie_id),
    CONSTRAINT chk_cinema_movies_available
        CHECK (is_available IN (0, 1))
);

-- ---------------------------------------------------------
-- 2. Activities (cleaning, advertisements, maintenance)
--    Catalog unique by (type, duration): the API reuses the existing
--    row or creates it when scheduling a projection.
-- ---------------------------------------------------------
CREATE TABLE Activities (
    activity_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR2(100) NOT NULL,
    duration_minutes    NUMBER(3) NOT NULL,
    type                VARCHAR2(20) NOT NULL,
    description         VARCHAR2(500),
    CONSTRAINT chk_activities_type
        CHECK (type IN ('CLEANING', 'ADVERTISEMENT', 'MAINTENANCE')),
    CONSTRAINT chk_activities_duration
        CHECK (duration_minutes BETWEEN 0 AND 240),
    CONSTRAINT uq_activities_type_duration UNIQUE (type, duration_minutes)
);

CREATE TABLE Movie_functions_activities (
    movie_functions_activity_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_function_id            NUMBER NOT NULL,
    activity_id                  NUMBER NOT NULL,
    created_by                   NUMBER NOT NULL,
    CONSTRAINT fk_mfa_movie_function
        FOREIGN KEY (movie_function_id) REFERENCES Movie_functions (movie_function_id),
    CONSTRAINT fk_mfa_activity
        FOREIGN KEY (activity_id) REFERENCES Activities (activity_id),
    CONSTRAINT fk_mfa_employee
        FOREIGN KEY (created_by) REFERENCES Employees (employee_id),
    CONSTRAINT uq_mfa_function_activity
        UNIQUE (movie_function_id, activity_id)
);

-- ---------------------------------------------------------
-- 3. Projection price, status and creation date
--    PRICE is only validated for new/updated rows (NOVALIDATE)
--    so the migration does not fail if functions without price exist.
-- ---------------------------------------------------------
ALTER TABLE Movie_functions ADD (
    price       NUMBER(10, 2),
    status      VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE Movie_functions MODIFY (price NOT NULL ENABLE NOVALIDATE);

ALTER TABLE Movie_functions ADD CONSTRAINT chk_movie_function_price
    CHECK (price > 0) ENABLE NOVALIDATE;

-- FINISHED is only assigned by the status job when the function ends.
ALTER TABLE Movie_functions ADD CONSTRAINT chk_movie_function_status
    CHECK (status IN ('ACTIVE', 'INACTIVE', 'CANCELLED', 'IN_PROGRESS', 'FINISHED'));

-- Schedule conflict lookups per theater and the status job.
CREATE INDEX ix_movie_functions_theater_time
    ON Movie_functions (theater_id, start_time, end_time);

CREATE INDEX ix_movie_functions_status_time
    ON Movie_functions (status, start_time, end_time);

-- ---------------------------------------------------------
-- 4. Automatic status change based on time
--    Oracle triggers only fire on INSERT/UPDATE/DELETE, never at a given
--    time; therefore a DBMS_SCHEDULER job runs every minute:
--    ACTIVE -> IN_PROGRESS when it starts and -> FINISHED when it ends.
-- ---------------------------------------------------------
CREATE OR REPLACE PROCEDURE refresh_movie_function_status AS
    v_now TIMESTAMP := CAST(SYSTIMESTAMP AT TIME ZONE 'America/Costa_Rica' AS TIMESTAMP);
BEGIN
    UPDATE Movie_functions
       SET status = 'IN_PROGRESS'
     WHERE status = 'ACTIVE'
       AND start_time <= v_now
       AND end_time > v_now;

    UPDATE Movie_functions
       SET status = 'FINISHED'
     WHERE status IN ('ACTIVE', 'IN_PROGRESS')
       AND end_time <= v_now;

    COMMIT;
END;
/

BEGIN
    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'MOVIE_FUNCTION_STATUS_JOB',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'REFRESH_MOVIE_FUNCTION_STATUS',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=MINUTELY;INTERVAL=1',
        enabled         => TRUE,
        comments        => 'Updates projection statuses according to their schedule'
    );
END;
/

-- Verification:
-- SELECT job_name, state, last_start_date, next_run_date
--   FROM user_scheduler_jobs WHERE job_name = 'MOVIE_FUNCTION_STATUS_JOB';
